# Encontrar inconsistências nas bases

Verficar os valores recebidos pela seguradora e cruzar os dados com os valores do nosso banco pra encontrar inconsistências

In [103]:
import pandas as pd

# importa os valores do extrato da seguradora
extrato_seguradora = pd.read_csv('extrato-seguradora.csv', dtype={'cpf': str})
# display(extrato_seguradora.head())

# separa o extrato por empresa
extrato_vertex = extrato_seguradora[extrato_seguradora['empresa'] == 'Vertex Logística']
extrato_sopro = extrato_seguradora[extrato_seguradora['empresa'] == 'Sopro Alimentos']
extrato_aurora = extrato_seguradora[extrato_seguradora['empresa'] == 'Aurora Clínicas']

# retira a coluna empresa e o indice do dataframe
extrato_vertex = extrato_vertex.reset_index(drop=True)
extrato_sopro = extrato_sopro.reset_index(drop=True)
extrato_aurora = extrato_aurora.reset_index(drop=True)

display(extrato_vertex.head())
display(extrato_sopro.head())
display(extrato_aurora.head())

,empresa,cpf,contribuicao_colaborador,contrapartida_empresa,total_linha
0,Vertex Logística,77382795675,214.18,107.09,321.27
1,Vertex Logística,34264099250,1051.38,525.69,1577.07
2,Vertex Logística,73278641728,1002.78,501.39,1504.17
3,Vertex Logística,47293918372,792.49,396.25,1188.74
4,Vertex Logística,94393545850,144.54,72.27,216.81

,empresa,cpf,contribuicao_colaborador,contrapartida_empresa,total_linha
0,Sopro Alimentos,39886322608,352.73,352.73,705.46
1,Sopro Alimentos,87563124314,358.04,358.04,716.08
2,Sopro Alimentos,88116658417,396.13,396.13,792.26
3,Sopro Alimentos,32322707198,220.36,220.36,440.72
4,Sopro Alimentos,31237190576,383.51,383.51,767.02

,empresa,cpf,contribuicao_colaborador,contrapartida_empresa,total_linha
0,Aurora Clínicas,17179666831,507.80,203.12,710.92
1,Aurora Clínicas,40767206363,1017.29,406.92,1424.21
2,Aurora Clínicas,71328020207,898.64,359.46,1258.10
3,Aurora Clínicas,33531338609,716.02,286.41,1002.43
4,Aurora Clínicas,97330735477,1119.25,447.70,1566.95

In [104]:
# importa os valores das contribuições de agosto de cada empresa
contribuicoes_vertex = pd.read_excel('contribuicoes-agosto.xlsx', sheet_name='Vertex Logística', dtype={'cpf': str})
contribuicoes_sopro = pd.read_excel('contribuicoes-agosto.xlsx', sheet_name='Sopro Alimentos', dtype={'cpf': str})
contribuicoes_aurora = pd.read_excel('contribuicoes-agosto.xlsx', sheet_name='Aurora Clínicas', dtype={'cpf': str})

display(contribuicoes_vertex.head())
# display(contribuicoes_sopro.head())
# display(contribuicoes_aurora.head())

           cpf                    nome  contribuicao_colaborador
0  73278641728     Ana Almeida Cardoso                   1002.78
1  34264099250       Ana Barbosa Klein                   1051.38
2  96180192766      Ana Ribeiro Santos                    236.08
3  94393545850   Beatriz Duarte Duarte                    144.54
4  59579724792  Beatriz Vieira Barbosa                    813.70

In [106]:
# df_colaboradores: cpf e salario

# importa os dados dos colaboradores que estão na folha de pagamento
colaboradores_vertex = pd.read_csv('colaboradores_vertex.csv', dtype={'cpf': str})
colaboradores_sopro = pd.read_csv('colaboradores_sopro.csv', dtype={'cpf': str})
colaboradores_aurora = pd.read_csv('colaboradores_aurora.csv', dtype={'cpf': str})

# remove as colunas nome, empresa, data_admissao, data_desligamento, status e o indice do dataframe
colaboradores_vertex = colaboradores_vertex.drop(columns=['nome', 'empresa', 'data_admissao', 'data_desligamento', 'status']).reset_index(drop=True)
colaboradores_sopro = colaboradores_sopro.drop(columns=['nome', 'empresa', 'data_admissao', 'data_desligamento', 'status']).reset_index(drop=True)
colaboradores_aurora = colaboradores_aurora.drop(columns=['nome', 'empresa', 'data_admissao', 'data_desligamento', 'status']).reset_index(drop=True)


display(colaboradores_vertex.head())
# display(colaboradores_sopro.head())
# display(colaboradores_aurora.head())

           cpf  salario
0  73278641728  16200.0
1  34264099250  11880.0
2  96180192766   7640.0
3  94393545850   4380.0
4  59579724792  10300.0

In [107]:
# cria um DataFrame consolidado com as contribuições e contrapartidas de cada empresa
df_vertex = colaboradores_vertex.merge(contribuicoes_vertex, on='cpf', how='left')
df_sopro = colaboradores_sopro.merge(contribuicoes_sopro, on='cpf', how='left')
df_aurora = colaboradores_aurora.merge(contribuicoes_aurora, on='cpf', how='left')

display(df_vertex.head())
# display(df_sopro.head())
# display(df_aurora.head())

           cpf  salario                    nome  contribuicao_colaborador
0  73278641728  16200.0     Ana Almeida Cardoso                   1002.78
1  34264099250  11880.0       Ana Barbosa Klein                   1051.38
2  96180192766   7640.0      Ana Ribeiro Santos                    236.08
3  94393545850   4380.0   Beatriz Duarte Duarte                    144.54
4  59579724792  10300.0  Beatriz Vieira Barbosa                    813.70

In [108]:
# crio um dataframe juntando o df da empresa com o extrato da seguradora, para comparar os valores de contribuições e contrapartidas com os valores do extrato
comparativo_vertex = df_vertex.merge(extrato_vertex, on='cpf', how='left', suffixes=('_agosto', '_extrato'))
comparativo_sopro = df_sopro.merge(extrato_sopro, on='cpf', how='left', suffixes=('_agosto', '_extrato'))
comparativo_aurora = df_aurora.merge(extrato_aurora, on='cpf', how='left', suffixes=('_agosto', '_extrato'))

display(comparativo_vertex.head())
# display(comparativo_sopro.head())
# display(comparativo_aurora.head())

,cpf,salario,nome,contribuicao_colaborador_agosto,empresa,contribuicao_colaborador_extrato,contrapartida_empresa,total_linha
0,73278641728,16200.0,Ana Almeida Cardoso,1002.78,Vertex Logística,1002.78,501.39,1504.17
1,34264099250,11880.0,Ana Barbosa Klein,1051.38,Vertex Logística,1051.38,525.69,1577.07
2,96180192766,7640.0,Ana Ribeiro Santos,236.08,Vertex Logística,236.08,118.04,354.12
3,94393545850,4380.0,Beatriz Duarte Duarte,144.54,Vertex Logística,144.54,72.27,216.81
4,59579724792,10300.0,Beatriz Vieira Barbosa,813.70,Vertex Logística,813.70,406.85,1220.55

In [111]:
# Filtra apenas as linhas onde os valores são diferentes
comparativo_vertex['diferenca_contribuicao'] = (
    comparativo_vertex['contribuicao_colaborador_agosto'] - comparativo_vertex['contribuicao_colaborador_extrato']
)

comparativo_aurora['diferenca_contribuicao'] = (
    comparativo_aurora['contribuicao_colaborador_agosto'] - comparativo_aurora['contribuicao_colaborador_extrato']
)

comparativo_sopro['diferenca_contribuicao'] = (
    comparativo_sopro['contribuicao_colaborador_agosto'] - comparativo_sopro['contribuicao_colaborador_extrato']
)

# Filtra apenas as linhas com diferença
diferencas_vertex = comparativo_vertex[comparativo_vertex['diferenca_contribuicao'] != 0]
diferencas_aurora = comparativo_aurora[comparativo_aurora['diferenca_contribuicao'] != 0]
diferencas_sopro = comparativo_sopro[comparativo_sopro['diferenca_contribuicao'] != 0]


print(diferencas_vertex.to_string(index=False))
print(diferencas_aurora.to_string(index=False))
print(diferencas_sopro.to_string(index=False))

        cpf  salario                    nome  contribuicao_colaborador_agosto          empresa  contribuicao_colaborador_extrato  contrapartida_empresa  total_linha  diferenca_contribuicao
14235297902   3060.0    Camila Klein Esteves                           141.68 Vertex Logística                            391.68                 183.60       575.28                  -250.0
52233099605   9780.0    Fabiana Rocha Duarte                           342.30 Vertex Logística                            432.30                 216.15       648.45                   -90.0
80362368937  12960.0 Helena Pacheco Ferreira                           489.89 Vertex Logística                            609.89                 304.95       914.84                  -120.0
10055891438   6000.0    Karina Xavier Xavier                           206.40              NaN                               NaN                    NaN          NaN                     NaN
22724828054   5470.0  Otavio Correia Ibrahim                           307.42              NaN                               NaN                    NaN          NaN                     NaN
91992558981  11130.0     Patricia Gomes Lima                           819.17 Vertex Logística                           1129.17                 564.59      1693.76                  -310.0
53752881330  13890.0 Simone Henriques Xavier                           641.72 Vertex Logística                            821.72                 410.86      1232.58                  -180.0
46007759962  13330.0   Vanessa Santos Duarte                           687.83              NaN                               NaN                    NaN          NaN                     NaN
Empty DataFrame
Columns: [cpf, salario, nome, contribuicao_colaborador_agosto, empresa, contribuicao_colaborador_extrato, contrapartida_empresa, total_linha, diferenca_contribuicao]
Index: []
       cpf  salario nome  contribuicao_colaborador_agosto         empresa  contribuicao_colaborador_extrato  contrapartida_empresa  total_linha  diferenca_contribuicao
9486660212   7810.0  NaN                              NaN Sopro Alimentos                            293.66                 293.66       587.32                     NaN

In [112]:
# Filtra linhas onde a contribuição do extrato está ausente (NaN)
nao_encontrados_vertex = comparativo_vertex[
    comparativo_vertex['contribuicao_colaborador_extrato'].isna()
]

nao_encontrados_sopro = comparativo_sopro[
    comparativo_sopro['contribuicao_colaborador_extrato'].isna()
]

nao_encontrados_aurora = comparativo_aurora[
    comparativo_aurora['contribuicao_colaborador_extrato'].isna()
]

print(nao_encontrados_vertex.to_string(index=False))
print(nao_encontrados_sopro.to_string(index=False))
print(nao_encontrados_aurora.to_string(index=False))

        cpf  salario                   nome  contribuicao_colaborador_agosto empresa  contribuicao_colaborador_extrato  contrapartida_empresa  total_linha  diferenca_contribuicao
10055891438   6000.0   Karina Xavier Xavier                           206.40     NaN                               NaN                    NaN          NaN                     NaN
22724828054   5470.0 Otavio Correia Ibrahim                           307.42     NaN                               NaN                    NaN          NaN                     NaN
46007759962  13330.0  Vanessa Santos Duarte                           687.83     NaN                               NaN                    NaN          NaN                     NaN
Empty DataFrame
Columns: [cpf, salario, nome, contribuicao_colaborador_agosto, empresa, contribuicao_colaborador_extrato, contrapartida_empresa, total_linha, diferenca_contribuicao]
Index: []
Empty DataFrame
Columns: [cpf, salario, nome, contribuicao_colaborador_agosto, empresa, contribuicao_colaborador_extrato, contrapartida_empresa, total_linha, diferenca_contribuicao]
Index: []

In [ ]:
# exporta o comparativo para um arquivo csv

comparativo_vertex.to_csv('comparativo_vertex.csv', index=False)
comparativo_sopro.to_csv('comparativo_sopro.csv', index=False)
comparativo_aurora.to_csv('comparativo_aurora.csv', index=False)

: